inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 3.2

Documentation:
  Enabled: false

Lint/SuppressedException:
  Exclude:
    - Rakefile

Lint/AssignmentInCondition:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'spec/requests/*'

Style/EmptyMethod:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/PercentLiteralDelimiters:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/ExpandPathArguments:
  Exclude:
    - 'Rakefile'
    - 'config.ru'
    - 'config/application.rb'
    - 'config/boot.rb'
    - 'config/environment.rb'
    - 'spec/rails_helper.rb'

Rails/ApplicationRecord:
  Exclude:
    - 'app/models/activity.rb'
    - 'app/models/appointment.rb'
    - 'app/models/bookable_slot.rb'
    - 'app/models/booking_request.rb'
    - 'app/models/guider_lookup.rb'
    - 'app/models/organisation_lookup.rb'
    - 'app/models/reporting_summary.rb'
    - 'app/models/schedule.rb'
    - 'app/models/slot.rb'
    - 'app/models/status_transition.rb'
    - 'app/models/user.rb'