sudo: false
language: ruby
services:
- redis-server
cache:
  bundler: true
  directories:
  - node_modules
  - tmp/cache/assets/test
  - vendor/assets/bower_components
node_js:
- '0.10'
before_install:
- gem update --system
before_script:
- npm install
- bundle exec rake db:create db:migrate RAILS_ENV=test
branches:
  except:
    - /^prototypes\/.*$/
notifications:
  slack:
    secure: eX03YQY/1x0boToVzccP6rMYqlrwuDT0NYcmDVSlUPKZTJiOtdv1BICdnqIjmFdAkyzh8nkVTXR1DysFfspbgInQw9USH3d7x8pakHE/wsxrcFcyO6G51QqX2BqVKqsGPrJ9PV+c+UrcguyYf4/y3z5L1EgpBXSnfX+o5lszhJ+9YVqVLKn84+gmGqoIvKdsDkPVmeJzlf6xeGS8k73pVDMcYNaFaJxX8mUQSgeN/Cn0FJd1Arj3iTb1KV3VZEVOfcpbbKLHCn+MmiaQPzlK4AHIZdBtMcDqUaX8pTC+p16g7pxcyN8DoJI35pfUxc2/tmns0YmdG1vCiT0z7y7tCoq1bGEPYNlmmbiC5WwcSXioCsL/LPXxB0v81IWIJGaa5Hmd9yMXgLQ9LrPBwVn71qBFSOKjjVv7XikVsIrp+j8ISq6Zfyp41vKQmtZsupgkYkWlR1Guzjg8pCCIcIP/0UyZQkli4Zo54Q3KPBPm0vWcnu2dolbC4LziYu8DgZ+TUE0/d3bAjgT3qGSAV4e/543hqkCe6BUq4Bjn5tJMc1rt218ssqlXkP2l65a5lk8+gCOvg5lrU0ARbtRRoxpobfKwZjoj6olc3WYt3TyBMaYTwrwUklGH/NcZDloIvyvNrMjVKOhI2sVxuAHTF4iu0DZDfcjSvTJPrdk/goHpe54=
