# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc71108dcf45c68925a6fda630e07a9d1ea344592dd93583e4804ab21258e15ed7069d8fba32520941d1119498c6575403dfc3ce966677b372208d232817c6d6

test:
  secret_key_base: ab6505a06e62dcb5a4e94e8252dd5685bbda7a0780c496e9222718c0a7a9c9faae3ddf062c04ae2c2483d649a6405bf166e5ad14e2215b83a092e8d8e5026e17

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
