name: "CI"
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      RAILS_ENV: test
      DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/planner_test'
      CLIVER_NO_VERIFY: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16
      - name: Install npm packages
        run: npm install
      - name: Set up database schema
        run: 'bundle exec rake db:create db:migrate'
      - name: Run tests and lint
        run: bundle exec rake
